In [1]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LinearRegression
from sklearn import preprocessing
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn import svm
from sklearn.metrics import jaccard_score
from sklearn.metrics import f1_score
from sklearn.metrics import log_loss
from sklearn.metrics import confusion_matrix, accuracy_score
import sklearn.metrics as metrics

In [2]:
df = pd.read_csv('Weather_Data.csv')
df.head()

,Date,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,...,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RainTomorrow
0,2/1/2008,19.5,22.4,15.6,6.2,0.0,W,41,S,SSW,...,92,84,1017.6,1017.4,8,8,20.7,20.9,Yes,Yes
1,2/2/2008,19.5,25.6,6.0,3.4,2.7,W,41,W,E,...,83,73,1017.9,1016.4,7,7,22.4,24.8,Yes,Yes
2,2/3/2008,21.6,24.5,6.6,2.4,0.1,W,41,ESE,ESE,...,88,86,1016.7,1015.6,7,8,23.5,23.0,Yes,Yes
3,2/4/2008,20.2,22.8,18.8,2.2,0.0,W,41,NNE,E,...,83,90,1014.2,1011.8,8,8,21.4,20.9,Yes,Yes
4,2/5/2008,19.7,25.7,77.4,4.8,0.0,W,41,NNE,W,...,88,74,1008.3,1004.8,8,8,22.5,25.5,Yes,Yes

In [15]:
df_processed = pd.get_dummies(data=df, columns=['RainToday', 'WindGustDir', 'WindDir9am', 'WindDir3pm'])
df_processed.replace(['No', 'Yes'], [0,1], inplace=True)
df_processed.drop('Date', axis=1, inplace=True)
df_processed = df_processed.astype(float)
df_processed.head()

C:\Users\Genia\AppData\Local\Temp\ipykernel_11404\3519027963.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_processed.replace(['No', 'Yes'], [0,1], inplace=True)

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustSpeed,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,...,WindDir3pm_NNW,WindDir3pm_NW,WindDir3pm_S,WindDir3pm_SE,WindDir3pm_SSE,WindDir3pm_SSW,WindDir3pm_SW,WindDir3pm_W,WindDir3pm_WNW,WindDir3pm_WSW
0,19.5,22.4,15.6,6.2,0.0,41.0,17.0,20.0,92.0,84.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
1,19.5,25.6,6.0,3.4,2.7,41.0,9.0,13.0,83.0,73.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,21.6,24.5,6.6,2.4,0.1,41.0,17.0,2.0,88.0,86.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,20.2,22.8,18.8,2.2,0.0,41.0,22.0,20.0,83.0,90.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,19.7,25.7,77.4,4.8,0.0,41.0,11.0,6.0,88.0,74.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

In [16]:
x = df_processed.drop(columns='RainTomorrow', axis=1)
y = df_processed['RainTomorrow']

Linear Regression

In [19]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=10)

In [21]:
LinearReg = LinearRegression().fit(x_train, y_train)
predictions = LinearReg.predict(x_test)

In [22]:
from sklearn.metrics import r2_score

LinearRegression_MAE = np.mean(np.absolute(predictions - y_test))
LinearRegression_MSE = np.mean((predictions - y_test) **2)
LinearRegression_R2 = r2_score(y_test, predictions)

In [25]:
report = pd.DataFrame({
    'MAE': [LinearRegression_MAE],
    'MSE': [LinearRegression_MSE],
    'R2': [LinearRegression_R2]
})

report.head()

        MAE       MSE        R2
0  0.256318  0.115721  0.427132

In [30]:
KNN = KNeighborsClassifier(n_neighbors=4).fit(x_train, y_train)
predictions = KNN.predict(x_test)

In [32]:
KNN_Accuracy_Score = accuracy_score(y_test, predictions)
KNN_JaccardIndex = jaccard_score(y_test, predictions)
KNN_F1_Score = f1_score(y_test,predictions)

report = pd.DataFrame({
    'Accuracy Score': [KNN_Accuracy_Score],
    'Jaccar Score': [KNN_JaccardIndex],
    'F1 Score': [KNN_F1_Score]
})

report.head()

   Accuracy Score  Jaccar Score  F1 Score
0        0.818321      0.425121   0.59661

Decision Tree

In [36]:
Tree = DecisionTreeClassifier(criterion='entropy', max_depth=4).fit(x_test, y_test)
predictions = Tree.predict(x_test)

In [39]:
Tree_Accuracy_Score = accuracy_score(y_test, predictions)
Tree_JaccardIndex =  jaccard_score(y_test, predictions)
Tree_F1_Score = f1_score(y_test, predictions)

report = pd.DataFrame({
    'Accuracy Score': [Tree_Accuracy_Score],
    'Jaccar Score': [Tree_JaccardIndex],
    'F1 Score': [Tree_F1_Score]
})

report.head()

   Accuracy Score  Jaccar Score  F1 Score
0        0.856489      0.520408  0.684564

Regresion logistica

In [41]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

In [42]:
LR = LogisticRegression(solver='liblinear').fit(x_train, y_train)

In [43]:
predictions = LR.predict(x_test)
predictions_proba = LR.predict_proba(x_test)

In [45]:
LR_Accuracy_Score = accuracy_score(y_test, predictions)
LR_JaccardIndex = jaccard_score(y_test, predictions)
LR_F1_Score = f1_score(y_test, predictions)
LR_Log_Loss = log_loss(y_test, predictions_proba)

report = pd.DataFrame({
    'Accuracy Score': [LR_Accuracy_Score],
    'Jaccar Score': [LR_JaccardIndex],
    'F1 Score': [LR_F1_Score],
    'Loss Log' : [LR_Log_Loss]
})

report.head()

   Accuracy Score  Jaccar Score  F1 Score  Loss Log
0        0.836641      0.509174  0.674772  0.380451

Support Vector Machine

In [46]:
SVM = svm.SVC().fit(x_train, y_train)

In [49]:
predictions = SVM.predict(x_test)

In [ ]:
SVM_Accuracy_Score = accuracy_score(y_test, predictions)
SVM_JaccardIndex = jaccard_score(y_test, predictions)
SVM_F1_Score = f1_score(y_test, predictions)

report = pd.DataFrame({
    'Accuracy Score': [SVM_Accuracy_Score],
    'Jaccar Score': [SVM_JaccardIndex],
    'F1 Score': [SVM_F1_Score],
})

report.head()

SyntaxError: invalid syntax (4124687438.py, line 8)

In [59]:
report = pd.DataFrame({
    'Model': ['SVM', 'KNN', 'Decision Tree', 'Logistic Regression'],
    'Accuracy Score': [SVM_Accuracy_Score, KNN_Accuracy_Score, Tree_Accuracy_Score, LR_Accuracy_Score],
    'Jaccar Score': [SVM_JaccardIndex, KNN_JaccardIndex, Tree_JaccardIndex, LR_JaccardIndex],
    'F1 Score': [SVM_F1_Score, KNN_F1_Score, Tree_F1_Score, LR_F1_Score],
    'LOG LOSS' : [None,None,None,LR_Log_Loss]
})

report.head()

                 Model  Accuracy Score  Jaccar Score  F1 Score  LOG LOSS
0                  SVM        0.722137      0.000000  0.000000       NaN
1                  KNN        0.818321      0.425121  0.596610       NaN
2        Decision Tree        0.856489      0.520408  0.684564       NaN
3  Logistic Regression        0.836641      0.509174  0.674772  0.380451